steps:
  - command: .buildkite/scripts/run_autoformat.py
    label: "autoformat"
  - wait
  - command: .buildkite/scripts/run_job.py common
    label: "common"
  - command: .buildkite/scripts/run_job.py display
    label: "display"
  - wait
  - command: .buildkite/scripts/run_job.py bags_api
    label: "bags API"
  - command: .buildkite/scripts/run_job.py bag_register
    label: "bag register"
  - command: .buildkite/scripts/run_job.py bag_replicator
    label: "bag replicator"
  - command: .buildkite/scripts/run_job.py bag_root_finder
    label: "bag root finder"
  - command: .buildkite/scripts/run_job.py bag_tagger
    label: "bag tagger"
  - command: .buildkite/scripts/run_job.py bag_tracker
    label: "bag tracker"
  - command: .buildkite/scripts/run_job.py bag_verifier
    label: "bag verifier"
  - command: .buildkite/scripts/run_job.py bag_unpacker
    label: "bag unpacker"
  - command: .buildkite/scripts/run_job.py bag_versioner
    label: "bag versioner"
  - command: .buildkite/scripts/run_job.py replica_aggregator
    label: "replica aggregator"
  - command: .buildkite/scripts/run_job.py bag_indexer
    label: "bag indexer"
  - command: .buildkite/scripts/run_job.py ingests_indexer
    label: "ingests indexer"
  - command: .buildkite/scripts/run_job.py file_finder
    label: "file finder"
  - command: .buildkite/scripts/run_job.py file_indexer
    label: "file indexer"
  - command: .buildkite/scripts/run_job.py ingests_worker
    label: "ingests worker"
  - command: .buildkite/scripts/run_job.py ingests_tracker
    label: "ingests tracker"
  - command: .buildkite/scripts/run_job.py ingests_api
    label: "ingests API"
  - command: .buildkite/scripts/run_job.py notifier
    label: "notifier"
  - command:
      pip3 install --user tox &&
      cd scripts &&
      /var/lib/buildkite-agent/.local/bin/tox -e py3
    label: "Test Python scripts"
  - wait
  - command: .buildkite/scripts/complete_build.py
    label: "tag commit as latest"
    if: build.branch == "main"
  - wait
  - label: release to stage
    if: build.branch == "main"
    plugins:
      - docker#v3.5.0:
          image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.6.11"
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--confirm",
              "release-deploy",
              "--from-label", "latest",
              "--environment-id", "stage",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600]
  - wait
  - label: send a test bag in stage
    if: build.branch == "main"
    plugins:
      - docker#v3.5.0:
          image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/amazon/aws-cli"
          command: [
            "lambda",
            "invoke",
            "--function-name", "arn:aws:lambda:eu-west-1:975596993436:function:end_to_end_bag_test--staging",
            "/dev/stdout"
          ]
